{
 "title": "App Monitoring (Direct)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "backend:8080, movies:8080, ratings:8080"
   }
  ]
 },
 "panels": [
  {
   "title": "Login Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_logins_total{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_in_progress_requests{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, endpoint) (\n  rate(http_request_duration_milliseconds_bucket{instance=\"${instance}\"}[1m])\n))",
     "legendFormat": "p50 - {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le, endpoint) (\n  rate(http_request_duration_milliseconds_bucket{instance=\"${instance}\"}[1m])\n))",
     "legendFormat": "p90 - {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, endpoint) (rate(http_request_duration_ms_bucket{instance=\"${instance}\"}[1m])))",
     "legendFormat": "p95 - {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, endpoint) (rate(http_request_duration_ms_bucket{instance=\"${instance}\"}[1m])))",
     "legendFormat": "p99 - {{endpoint}}"
    },
    {
     "expr": "sum by (endpoint) (rate(http_request_duration_ms_sum{instance=\"${instance}\"}[1m])) / sum by (endpoint) (rate(http_request_duration_ms_count{instance=\"${instance}\"}[1m]))",
     "legendFormat": "avg - {{endpoint}}"
    },
    {
     "expr": "min_over_time((sum by (endpoint) (rate(http_request_duration_ms_sum{instance=\"${instance}\"}[1m])) / sum by (endpoint) (rate(http_request_duration_ms_count{instance=\"${instance}\"}[1m])))[1m:1m])",
     "legendFormat": "min - {{endpoint}}"
    },
    {
     "expr": "max_over_time((sum by (endpoint) (rate(http_request_duration_ms_sum{instance=\"${instance}\"}[1m])) / sum by (endpoint) (rate(http_request_duration_ms_count{instance=\"${instance}\"}[1m])))[1m:1m])",
     "legendFormat": "max - {{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{instance=\"${instance}\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP 500 Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "http_requests_total{status=\"500\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Process Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{otel_scope_name=\"OpenTelemetry.Instrumentation.Process\",otel_scope_version=\"1.11.0-beta.2\", instance=\"${instance}\"}/1048576"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "process_memory_virtual_bytes{otel_scope_name=\"OpenTelemetry.Instrumentation.Process\",otel_scope_version=\"1.11.0-beta.2\",instance=\"${instance}\"}/10485760"
    }
   ]
  },
  {
   "title": "CPU Time (User)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "process_cpu_time_seconds_total{otel_scope_name=\"OpenTelemetry.Instrumentation.Process\",otel_scope_version=\"1.11.0-beta.2\",process_cpu_state=\"user\", instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "CPU Time (System)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "process_cpu_time_seconds_total{otel_scope_name=\"OpenTelemetry.Instrumentation.Process\",otel_scope_version=\"1.11.0-beta.2\",process_cpu_state=\"system\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "process_cpu_count{otel_scope_name=\"OpenTelemetry.Instrumentation.Process\",otel_scope_version=\"1.11.0-beta.2\", instance=\"${instance}\"}"
    }
   ]
  }
 ]
}