@ratings_HostAddress = http://localhost:5272

### Get all ratings
GET {{ratings_HostAddress}}/
Accept: application/json

### Get ratings by movie ID
GET {{ratings_HostAddress}}/1
Accept: application/json

### Health Check - Liveness
GET {{ratings_HostAddress}}/health/live
Accept: application/json

### Health Check - Readiness
GET {{ratings_HostAddress}}/health/ready
Accept: application/json

### Get metrics
GET {{ratings_HostAddress}}/metrics