receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: "0.0.0.0:8889"
    
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
       insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:
  attributes:
    actions:
      - key: exported_instance
        action: insert
        value: ${HOSTNAME}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki]